### ISSUE TITLE
Wrong image extension problem

### ISSUE THREAD

**Issue by ra100** [ra100/shoutbox-widget#18]
When trying to upload .jpg file but it's really PNG. This should pass, or automatically rename file to match format.
```
identify.im6: Not a JPEG file: starts with 0x5b 0x6f @ error/jpeg.c/JPEGErrorHandler/316.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

**Comment by ra100** [comment]
fixed by c88e9b6
